/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    Countdown: typeof import('./src/components/countdown/countdown.vue')['default']
    FooterBottom: typeof import('./src/components/footer-bottom/footer-bottom.vue')['default']
    HeaderTop: typeof import('./src/components/header-top/header-top.vue')['default']
    IEpCirclePlus: typeof import('~icons/ep/circle-plus')['default']
    IEpShare: typeof import('~icons/ep/share')['default']
    LoginDialog: typeof import('./src/components/login-dialog/login-dialog.vue')['default']
    PayDialog: typeof import('./src/components/pay-dialog/pay-dialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadImg: typeof import('./src/components/upload-img/upload-img.vue')['default']
  }
}
